### ISSUE TITLE
Group Milestone - Implementation (Sprint 1)

### ISSUE THREAD

**Issue by eclipsegst** [expense-manager/expense-manager#20]
/cc @codepathreview @codepath here is our sprint one work complete check list: 

- [X] setup and configure Parse Server
- [X] login
- [X] sign up
- [X] sign out
- [X] app navigation
- [X] create/update/delete expense both in server and local database
- [X] create/update/delete category both in server and local database
- [X] report detail, category based graph
- [X] take/choose/upload expense photo

## Video Walkthrough
Here's a walkthrough of implemented user stories:

![expense-manager-login-sign-up](https://cloud.githubusercontent.com/assets/3318745/17874810/a14f4522-6893-11e6-8a84-dc806787573d.gif)

![expense-manager-expense](https://cloud.githubusercontent.com/assets/3318745/17874777/5e11bab0-6893-11e6-88a2-ac1fa86e72c3.gif)

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes

* Tasks are well defined and seem achievable in the given timeframe
* Good work dividing tasks among team members. This is critical in working as a team and also gives equal learning opportunity to everyone involved
* Good to see everyone is [contributing](https://github.com/expense-manager/expense-manager/commits/master) to the project
* Nice work creating and distributing tasks to create database schema and models.
* Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project. You can maintain this on the ReadMe.
* Depending on the strategy your group has come up with, consider creating regular check ins to sync up your code to avoid having multiple errors at the end.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Consider incorporating as many screens as possible in this sprint so you can have enough time to add UI polish and advanced features later on. It is those little extra things you do that make everything feel more polished and desirable to use. Look forward to what you all come up with.
