### ISSUE TITLE
Group Milestone - Iterating (Sprint 2)

### ISSUE THREAD

**Issue by eclipsegst** [expense-manager/expense-manager#25]
/cc @codepathreview @codepath here is our sprint two work complete check list: 

core user stories:
- [X] user can create/read/update/delete expense both in server and local database
- [X] user can create/read/update/delete category both in server and local database
- [X] user can take/choose/upload expense photo
- [X] user can click to view expense photos in view pager 
- [X] user can search expense by date range and/or by category
- [X] user can click to view any weekly/monthly/yearly detail report
    - [X] weekly/monthly/yearly vary by user's expense history and updates in real-time
- [X] detail report includes category analysis (pie chart) and date analysis (bar chart)
    - [X] category analysis includes all categories that have expenses and no category
    - [X] date analysis range updates in real-time
    - [X] user can click to view expense data collected by detail report with filters applied
 
other:
- [X] login
- [X] sign up
- [X] sign out
- [X] profile page

## Video Walkthrough
Here's a walkthrough of implemented user stories:
![expense-manager](https://cloud.githubusercontent.com/assets/3318745/18069788/03820bbe-6e0f-11e6-97fc-bce6e426b52a.gif)
![expense-manager-expense2](https://cloud.githubusercontent.com/assets/3318745/18070386/0b531bc2-6e13-11e6-8b12-a88690bbee29.gif)

Plan for Sprint 3:
- Update UI
- Add photo preview page
- Add weekly/monthly report notification
- Fix bugs
- Build group/organization based expense management

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

* Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
* Good to see you have tasks/issues being worked on actively and have plans in place for Sprint 3.
* Good to see that you have already started adding UI polish to your app
* Good to see that your team had regular commits/pull-requests to merge the code
* Consider improving your test coverage by incorporating positive as well as negative testing to determine if your app handles improper user behavior correctly.
* Keep working on integrating the core flows and make sure all pieces fit together perfectly.
* Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
* While working on polishing your app for next sprint, remember that your app follows the [android design guidelines] (http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns] (http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
